package com.wildlife.app.wildlife.app.models.constants;

public interface DBColumnConstants {
    String TBL_CONST_ANIMAL_TYPE = "TBL_CONST_ANIMAL_TYPE";
    String TBL_CONST_EXISTENCE_STATUS = "TBL_CONST_EXISTENCE_STATUS";
    String TBL_CONST_FOOD_HABIT_TYPE = "TBL_CONST_FOOD_HABIT_TYPE";
    String TBL_CONST_COUNTRY = "TBL_CONST_COUNTRY";
    String TBL_CONST_STATE = "TBL_CONST_STATE";
    String TBL_ANIMAL = "TBL_ANIMAL";
    String TBL_ANIMAL_OTHER_NAME = "TBL_ANIMAL_OTHER_NAME";
    String TBL_LOCATION = "TBL_LOCATION";
    String TBL_TOUR = "TBL_TOUR";
    String TBL_REFERENCE = "TBL_REFERENCE";
    String TBL_MENU_ITEM = "TBL_MENU_ITEM";

    String COL_ANIMAL_TYPE_ID = "ANIMAL_TYPE_ID";
    String COL_ANIMAL_TYPE_NAME = "ANIMAL_TYPE_NAME";
    String COL_ANIMAL_TYPE_DEFINITION = "ANIMAL_TYPE_DEFINITION";

    String COL_FOOD_HABIT_TYPE_ID = "FOOD_HABIT_TYPE_ID";
    String COL_FOOD_HABIT_TYPE = "FOOD_HABIT_TYPE";
    String COL_FOOD_HABIT_TYPE_DEFINITION = "FOOD_HABIT_TYPE_DEFINITION";

    String COL_EXISTENCE_STATUS_ID = "EXISTENCE_STATUS_ID";
    String COL_EXISTENCE_STATUS = "EXISTENCE_STATUS";
    String COL_EXISTENCE_STATUS_DESCRIPTION = "EXISTENCE_STATUS_DESCRIPTION";

    String COL_TBL_COUNTRY_CODE = "COUNTRY_CODE";
    String COL_TBL_COUNTRY_NAME = "COUNTRY_NAME";
    String COL_TBL_COUNTRY_ISD = "COUNTRY_ISD";

    String COL_TBL_STATE_CODE = "STATE_CODE";
    String COL_TBL_STATE_NAME = "STATE_NAME";

    String COL_TBL_LOCATION_ID = "LOCATION_ID";
    String COL_TBL_LOCATION_NAME = "LOCATION_NAME";
    String COL_TBL_LOCATION_AREA = "LOCATION_AREA";

    String COL_TBL_ANIMAL_ID = "ANIMAL_ID";
    String COL_TBL_ANIMAL_NAME = "ANIMAL_NAME";
    String COL_TBL_ANIMAL_FIRST_SPOTTING_DATE = "ANIMAL_FIRST_SPOTTING_DATE";
    String COL_TBL_ANIMAL_SCIENTIFIC_NAME = "ANIMAL_SCI_NAME";
    String COL_TBL_ANIMAL_OTHER_NAME_ID = "ANIMAL_OTHER_NAME_ID";
    String COL_TBL_ANIMAL_OTHER_NAME = "ANIMAL_OTHER_NAME";
    String COL_TBL_ANIMAL_GENDER = "ANIMAL_GENDER";

    String JOIN_COL_LOCATION_ID = "LOCATION_TBL_LOCATION_ID";
    String JOIN_COL_ANIMAL_ID = "ANIMAL_TBL_ANIMAL_ID";
    String JOIN_TBL_ANIMAL_LOCATION_MAPPING = "ANIMAL_LOCATION_MAPPING";

    String COL_TBL_MENU_ITEM_ID ="MENU_ITEM_ID";
    String COL_TBL_MENU_ITEM_LINK ="MENU_ITEM_LINK";
    String COL_TBL_MENU_ITEM_ALLOWED_FOR ="MENU_ITEM_ALLOWED_FOR";
    String COL_TBL_MENU_ITEM_MENU_TEXT ="MENU_ITEM_TEXT";

    String COL_TBL_TOUR_ID ="TOUR_ID";
    String COL_TBL_TOUR_START_DATE ="TOUR_START_DATE";
    String COL_TBL_TOUR_END_DATE ="TOUR_END_DATE";
    String COL_TBL_TOUR_LOCATION ="TOUR_LOCATION";
}
